/** Generates the sensor-pack evidence block in docs/support-matrix.md.
 *
 * The registry owns pack definitions. This renderer is intentionally a consumer of
 * those manifests instead of a second hand-written list of tools or versions.
 */
import fs from 'fs';
import path from 'path';
import { execFileSync } from 'child_process';
import { parseSensorPack } from '../src/commands/sensors/compatibility/contract';
import type { ParsedSensorPack } from '../src/commands/sensors/compatibility/types';

export const SENSOR_BEGIN_MARKER = '<!-- BEGIN GENERATED: sensor-pack-support -->';
export const SENSOR_END_MARKER = '<!-- END GENERATED: sensor-pack-support -->';
export const SENSOR_PACKS = ['generic', 'js-ts', 'python', 'shell'] as const;
export const SENSOR_DOC_PATH = path.resolve(__dirname, '..', '..', 'docs', 'support-matrix.md');
export const R3_PREPUBLICATION_FIXTURE_RELATIVE_PATH = 'tests/fixtures/sensor-support-matrix/registry';
/**
 * The CLI R3 contract is implemented before the baseline registry publishes its
 * v2 manifests. The generated matrix intentionally renders this pinned fixture,
 * never an invented description of an unpublished registry release.
 */
export const R3_PREPUBLICATION_FIXTURE_PURPOSE = 'R3 pre-publication contract fixture';
export const R3_PUBLISHED_REGISTRY_TAG = 'v2.0.0';
export const R3_PUBLISHED_REGISTRY_COMMIT = 'c35c087a0801c0b4e69e0a4ac3eafef9ecdf37cd';

/**
 * Extract the registry-owned certification matrix without copying or rewording it.
 * `SUPPORT.md` is generated by the registry from its manifests and frozen tool pins;
 * this consumer must preserve that published evidence rather than infer certification
 * from a compatibility range.
 */
export function extractPublishedSupportMetadata(source: unknown): string {
    if (typeof source !== 'string' || source.length === 0) {
        throw new Error('published sensor support metadata must be non-empty text');
    }
    const begin = '<!-- BEGIN GENERATED: sensor-pack-support -->';
    const end = '<!-- END GENERATED: sensor-pack-support -->';
    const starts = source.split(begin).length - 1;
    const ends = source.split(end).length - 1;
    if (starts !== 1 || ends !== 1) {
        throw new Error('published sensor support metadata requires exactly one generated marker pair');
    }
    const start = source.indexOf(begin) + begin.length;
    const finish = source.indexOf(end);
    if (finish <= start) throw new Error('published sensor support metadata has invalid marker order');
    const metadata = source.slice(start, finish).trim();
    if (!metadata.includes('| Pack | Sensor | Variant | Tool | Certified range | Supported OS | OS certification evidence | Status | Evidence |')) {
        throw new Error('published sensor support metadata lacks the certification table');
    }
    if (!metadata.includes('Status: `certified` has a matching frozen tool pin;')) {
        throw new Error('published sensor support metadata lacks certification status semantics');
    }
    return metadata;
}

function exactArgument(argv: readonly string[], flag: string): string {
    const index = argv.indexOf(flag);
    if (index === -1 || argv[index + 1] === undefined || argv[index + 1].startsWith('--') || index !== argv.lastIndexOf(flag)) {
        throw new Error(`sensor support matrix requires exactly one ${flag} <value>`);
    }
    return argv[index + 1];
}

/** Refuse a mutable sibling checkout: published evidence is valid only for this immutable release. */
export function verifyPublishedRegistryIdentity(registryRoot: unknown, tag: unknown, commit: unknown): void {
    const root = registryPath(registryRoot);
    if (tag !== R3_PUBLISHED_REGISTRY_TAG || commit !== R3_PUBLISHED_REGISTRY_COMMIT) {
        throw new Error(`sensor support matrix requires published registry ${R3_PUBLISHED_REGISTRY_TAG}@${R3_PUBLISHED_REGISTRY_COMMIT}`);
    }
    const resolve = (revision: string): string => {
        try {
            return execFileSync('git', ['-C', root, 'rev-parse', revision], { encoding: 'utf8', stdio: ['ignore', 'pipe', 'pipe'] }).trim();
        } catch {
            throw new Error(`published registry root must be a git checkout at ${R3_PUBLISHED_REGISTRY_TAG}`);
        }
    };
    const head = resolve('HEAD');
    const taggedCommit = resolve(`${tag}^{commit}`);
    if (head !== commit) throw new Error(`published registry HEAD ${head} does not match expected commit ${commit}`);
    if (taggedCommit !== commit) throw new Error(`published registry tag ${tag} resolves to ${taggedCommit}, expected commit ${commit}`);
}

function registryPath(value: unknown): string {
    if (typeof value !== 'string' || value.trim().length === 0 || value.includes('\0')) {
        throw new Error('sensor support matrix requires a non-empty --registry-root');
    }
    return path.resolve(value);
}

function packPath(registryRoot: string, name: string): string {
    if (!SENSOR_PACKS.includes(name as typeof SENSOR_PACKS[number])) throw new Error(`unsupported first-party pack: ${name}`);
    return path.join(registryRoot, 'sensor-packs', name, 'pack.json');
}

export function parseRegistrySensorPacks(registryRoot: unknown): Array<{ name: string; parsed: ParsedSensorPack }> {
    const root = registryPath(registryRoot);
    return SENSOR_PACKS.map((name) => {
        const file = packPath(root, name);
        const stat = fs.lstatSync(file);
        if (!stat.isFile() || stat.isSymbolicLink()) throw new Error(`sensor pack must be a regular file: ${file}`);
        let source: unknown;
        try { source = JSON.parse(fs.readFileSync(file, 'utf8')); } catch (error) {
            throw new Error(`cannot parse sensor pack ${name}: ${error instanceof Error ? error.message : String(error)}`);
        }
        return { name, parsed: parseSensorPack(source, file) };
    });
}

function variants(pack: Extract<ParsedSensorPack, { kind: 'v2' }>['pack']): string {
    return Object.entries(pack.sensors).flatMap(([sensor, definition]) => definition.variants.map((variant) =>
        `\`${sensor}/${variant.id}\`: ${variant.requirements.tool} ${variant.requirements.toolRange}; ${variant.requirements.runtime} ${variant.requirements.runtimeRange}; certified ${variant.certifiedRange}`,
    )).join('<br>');
}

function publishedSupportMetadata(registryRoot: string): string | null {
    const file = path.join(registryRoot, 'sensor-packs', 'SUPPORT.md');
    if (!fs.existsSync(file)) return null;
    const stat = fs.lstatSync(file);
    if (!stat.isFile() || stat.isSymbolicLink()) throw new Error(`published sensor support metadata must be a regular file: ${file}`);
    return extractPublishedSupportMetadata(fs.readFileSync(file, 'utf8'));
}

/** Pure renderer used by freshness tests and the documentation command. */
export function renderSensorSupportMatrix(registryRoot: unknown): string {
    const root = registryPath(registryRoot);
    const publishedMetadata = publishedSupportMetadata(root);
    const lines = [
        publishedMetadata === null
            ? `### Sensor-pack compatibility contract (${R3_PREPUBLICATION_FIXTURE_PURPOSE})`
            : '### Sensor-pack compatibility contract (published registry evidence)',
        '',
        '| Pack | Contract | Version-aware variants and certified ranges | Evidence status |',
        '|---|---|---|---|',
    ];
    for (const { name, parsed } of parseRegistrySensorPacks(root)) {
        if (parsed.kind === 'legacy') {
            lines.push(`| \`${name}\` | legacy pack | No v2 variants declared | compatible-unverified — migrate the pack before claiming version certification |`);
        } else {
            lines.push(`| \`${name}\` | pack schema v2 | ${variants(parsed.pack)} | ${publishedMetadata === null ? 'Fixture-declared ranges only; real-tool and OS certification awaits published registry release evidence' : 'Published compatibility contract; certification evidence is reproduced below from the registry' } |`);
        }
    }
    lines.push('');
    if (publishedMetadata === null) {
        lines.push('> Generated from the pinned R3 pre-publication contract fixture, not the published `awm-baseline-registry` manifests. **Do not edit by hand** — `npm run docs:matrix:prepublication` regenerates this fixture-only block. T13 verifies the actual registry tag and release evidence.');
    } else {
        lines.push('');
        lines.push('#### Published certification evidence');
        lines.push('');
        lines.push(publishedMetadata);
        lines.push('');
        lines.push('> Generated from the supplied published `awm-baseline-registry` root. Certification states, frozen pins, and OS evidence are registry-owned metadata reproduced verbatim; **do not edit by hand**.');
    }
    return lines.join('\n');
}

export function spliceSensorSupportMatrix(markdown: string, generated: string): string {
    const begin = markdown.indexOf(SENSOR_BEGIN_MARKER);
    const end = markdown.indexOf(SENSOR_END_MARKER);
    if (begin === -1 || end === -1 || end < begin) throw new Error(`support-matrix.md lacks ${SENSOR_BEGIN_MARKER} / ${SENSOR_END_MARKER}`);
    // Preserve the line ending of the block this renderer owns. Another generated
    // block may legitimately have a different EOL during a Windows checkout.
    const eol = markdown.slice(begin, end).includes('\r\n') ? '\r\n' : '\n';
    const block = generated.split('\n').join(eol);
    return markdown.slice(0, begin + SENSOR_BEGIN_MARKER.length) + eol + eol + block + eol + eol + markdown.slice(end);
}

export function registryRootFromArgs(argv: readonly string[]): string {
    return registryPath(exactArgument(argv, '--registry-root'));
}

/* istanbul ignore next: command shell is covered through exported functions. */
if (require.main === module) {
    const argv = process.argv.slice(2);
    const root = registryRootFromArgs(argv);
    const stdout = argv.includes('--stdout');
    if (argv.includes('--prepublication-fixture')) {
        if (argv.filter((value) => value === '--prepublication-fixture').length !== 1 || argv.filter((value) => value === '--stdout').length > 1 || (argv.length !== 3 && argv.length !== 4)) {
            throw new Error('sensor support matrix fixture mode accepts only --registry-root <path> --prepublication-fixture [--stdout]');
        }
    } else {
        verifyPublishedRegistryIdentity(root, exactArgument(argv, '--registry-tag'), exactArgument(argv, '--registry-commit'));
    }
    if (stdout) {
        process.stdout.write(`${renderSensorSupportMatrix(root)}\n`);
        process.exit(0);
    }
    const current = fs.readFileSync(SENSOR_DOC_PATH, 'utf8');
    fs.writeFileSync(SENSOR_DOC_PATH, spliceSensorSupportMatrix(current, renderSensorSupportMatrix(root)), 'utf8');
    process.stdout.write('support-matrix.md sensor-pack evidence regenerated from registry manifests\n');
}
