import { capabilityReceiptDigest } from '../../src/core/model-policy/capabilities';
import type { ApprovedPolicy, CapabilityReceipt } from '../../src/core/model-policy/types';

export const routingRuntime = { target: 'codex' as const, kind: 'native', version: '1.0.0', accountScopeDigest: '0'.repeat(64) };
export const routingSelection = (value: 'medium' | 'high') => ({ selector: { kind: 'model' as const, id: 'm' }, effort: { kind: 'explicit' as const, value } });
export function routingApproval() {
    const policy: ApprovedPolicy = { schema: 'approved-model-policy/v1', content: { schema: 'model-policy/v1', mappings: [{ target: 'codex', runtimeKind: 'native', profiles: { mechanical: routingSelection('medium'), integration: routingSelection('medium'), judgment: routingSelection('medium') }, fullCapability: routingSelection('high'), degradation: { allowMissingModelOverride: false, allowMissingEffortOverride: false, allowMissingObservedIdentity: false } }], implementationBudget: { maxAttempts: 3, escalation: ['mechanical', 'integration', 'judgment'], judgmentEfforts: ['medium', 'high'] } }, contentDigest: 'a'.repeat(64), approval: { approvedAt: '2026-09-17T00:00:00.000Z', approvalId: 'approval-1' }, lineage: { previousDigest: null } };
    const capabilities: CapabilityReceipt = { schema: 'routing-capabilities/v1', runtime: routingRuntime, recordedAt: '2026-09-17T00:00:00.000Z', expiresAt: '2026-09-18T00:00:00.000Z', capabilities: { artifactDelivery: 'unverified', interactiveExecution: 'supported', unattendedController: 'supported', nativeSubagents: 'unverified', modelOverride: 'supported', effortOverride: 'supported', observedModelEvidence: 'supported', durableResume: 'unverified' }, availableSelections: [routingSelection('medium'), routingSelection('high')], evidence: (['interactiveExecution', 'unattendedController', 'modelOverride', 'effortOverride', 'observedModelEvidence'] as const).map(capability => ({ capability, kind: 'native-control' as const, receiptDigest: 'a'.repeat(64) })), approval: { approvalId: 'approval-1', snapshotDigest: 'a'.repeat(64) } };
    return { policy, capabilities, checkedAt: new Date('2026-09-17T12:00:00.000Z') };
}
export const routingEnvelope = { schema: 'routing-envelope/v1' as const, runtime: routingRuntime, role: 'implementer', sliceId: 'S1', requestedProfile: 'mechanical' as const, effectiveProfile: 'mechanical' as const, resolved: routingSelection('medium'), outcome: 'native' as const, unavailableEvidence: [], policyDigest: 'a'.repeat(64), capabilityDigest: capabilityReceiptDigest(routingApproval().capabilities), planDigest: 'c'.repeat(64), executionDigest: 'd'.repeat(64) };
